#!/bin/bash

#PBS -N d2q9-bgk
#PBS -j oe
#PBS -o d2q9-bgk128.out
#PBS -q veryshort
#PBS -l nodes=1:ppn=16,walltime=00:10:00

# Change the working directory (default is home directory)
cd "$PBS_O_WORKDIR"

echo "Running on host: $(hostname)"
echo "Time is: $(date)"
echo "Directory is: $(pwd)"
echo "PBS job ID is: $PBS_JOBID"
echo "This jobs runs on the following machines: $(cat "$PBS_NODEFILE" | uniq)"
echo

export OMP_NUM_THREADS=1
export OMP_PROC_BIND=true

# Run the executable
./d2q9-bgk input_128x128.params obstacles_128x128.dat
# ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
